import {buildY004EditCues, validateY004Windows, y004ActiveTextCue,y004CueOpacity,Y004_PROVISIONAL_EDIT_WINDOWS,Y004_SAFE_MARGIN_PX} from './editorial';
import type {Y004EditWindow} from './editorial';
const ok=(v:boolean,message:string)=>{if(!v)throw new Error(message);};
const fails=(fn:()=>unknown,label:string)=>{let threw=false;try{fn();}catch{threw=true;}ok(threw,label);};
const cues=buildY004EditCues(Y004_PROVISIONAL_EDIT_WINDOWS,720);
ok(cues.length===5,'five cues and an intentionally text-free high drive');
ok(cues[0].line1==='THE REAR WHEELS'&&cues[0].line2==='TURN TOO.','hook exact text');
ok(cues[2].line1==='LOWER SPEED'&&cues[2].line2==='AGILITY','low text');
ok(cues[3].line1==='HIGHER SPEED'&&cues[3].line2==='STABILITY','high text');
ok(cues[4].treatment==='signature'&&cues[4].startFrame>600,'exit signature after drive-off begins');
ok(y004ActiveTextCue(415,cues)===undefined,'no oversized title over high driving');
ok(y004ActiveTextCue(285,cues)?.segmentId==='high-explain','high cut boundary');
ok(y004ActiveTextCue(284,cues)?.segmentId==='low-explain','low side of match cut');
ok(y004CueOpacity(0,cues[0])===0 && y004CueOpacity(10,cues[0])>0,'smooth opening');
ok(y004CueOpacity(720,cues[4])===0 && y004CueOpacity(800,cues[0])===0,'out-of-range invisible');
ok(Y004_SAFE_MARGIN_PX.x>=72&&Y004_SAFE_MARGIN_PX.top>=132,'mobile safe area');
const displaced=Y004_PROVISIONAL_EDIT_WINDOWS.map(w=>({...w}));
displaced[1]={...displaced[1],startFrame:83};
fails(()=>validateY004Windows(displaced,720),'reject overlaps');
fails(()=>validateY004Windows(Y004_PROVISIONAL_EDIT_WINDOWS,721),'reject wrong end');
fails(()=>validateY004Windows(Y004_PROVISIONAL_EDIT_WINDOWS.slice().reverse(),720),'reject reverse');
fails(()=>validateY004Windows(Y004_PROVISIONAL_EDIT_WINDOWS,719.5),'reject fractional frame count');
const retimed:Y004EditWindow[]=Y004_PROVISIONAL_EDIT_WINDOWS.map((w,i)=>({segmentId:w.segmentId,startFrame:i===0?0:w.startFrame+((i>=3)?6:0),endFrame:w.endFrame+((i>=2)?6:0)}));
validateY004Windows(retimed,726);
ok(buildY004EditCues(retimed,726)[3].startFrame===291,'accept retimed film after manager locks it');
for(const frame of [420,0,285,4,715,88,150,420])ok(JSON.stringify(buildY004EditCues(retimed,726))===JSON.stringify(buildY004EditCues(retimed,726)),'deterministic out-of-order');
console.log('YUNEX 004 D editorial tests: PASS (20 assertions including timeline guardrails)');
