'use strict';
const fs=require('fs');
const crypto=require('crypto');
const path=require('path');
const root=path.resolve(__dirname,'../../../../..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const assert=(ok,msg)=>{if(!ok)throw new Error(msg);};
const count=(src,needle)=>src.split(needle).length-1;
const trackWorld=read('src/video002/trackUpgrade/TrackWorld.tsx');
const preview=read('src/TrackPreview.tsx');
const integrated=read('src/video002/Video002Integrated.tsx');
assert(count(trackWorld,'<RoadSurfaces')===1,'RoadSurfaces must mount once');
assert(count(trackWorld,'<TrackFurniture')===1,'TrackFurniture must mount once');
assert(count(trackWorld,'<TrackVegetation')===1,'TrackVegetation must mount once');
assert(count(trackWorld,'<TrackLighting')===1,'TrackLighting must mount once');
assert(trackWorld.includes('TRACK_ROOT_POSITION:[number,number,number]=[-1,-0.028,0]'),'shared root position drift');
assert(trackWorld.includes('TRACK_ROOT_ROTATION:[number,number,number]=[0,Math.PI,0]'),'shared root rotation drift');
assert(trackWorld.includes('legacyKerb={false} legacyRail={false} legacyVegetation={false}'),'legacy replacements not suppressed');
assert(trackWorld.indexOf('</group>')<trackWorld.indexOf('<TrackLighting'),'TrackLighting must be outside shared rotated group');
assert(preview.includes('legacyKerb=true,legacyRail=true,legacyVegetation=true'),'YUNEX 001/default legacy visibility changed');
assert(preview.includes('{legacyKerb&&<Kerb/>}{legacyRail&&<Rail/>}'),'legacy kerb/rail are not conditionally suppressed');
assert(preview.includes('{legacyVegetation&&<group>'),'legacy vegetation is not conditionally suppressed');
assert(integrated.includes("import {TrackWorld} from './trackUpgrade/TrackWorld';"),'integrated scene missing TrackWorld');
assert(!integrated.includes("import {TechnicalTrackWorld} from '../TrackPreview';"),'integrated scene still mounts TechnicalTrackWorld directly');
assert(!integrated.includes("<hemisphereLight args={['#e8efec','#30362f',1.48]}/>") ,'legacy hemisphere light still present');
assert(!integrated.includes('toneMappingExposure=1.02'),'legacy exposure still present');
assert(integrated.includes('gl.shadowMap.enabled=true'),'renderer shadows not enabled');
assert(integrated.includes('gl.shadowMap.type=THREE.PCFSoftShadowMap'),'PCFSoftShadowMap missing');
assert(integrated.includes('gl.toneMappingExposure=0.94'),'target exposure missing');
assert(integrated.includes('object.castShadow=true'),'Porsche castShadow missing');
assert(integrated.includes('<TrackWorld quality="final" seed={2103}/>'),'TrackWorld final mount missing');
assert(/gl=\{\{antialias:true,alpha:false,preserveDrawingBuffer:true\}\}\s+shadows/.test(integrated),'ThreeCanvas shadows prop missing');
const car=fs.readFileSync(path.join(root,'../cars/porsche-911-gt3-rs-992/model.glb'));
const digest=crypto.createHash('sha256').update(car).digest('hex');
assert(digest==='1c73fcb138c31e2b1d5ed126a2412074bb17f8e960b355436f28139bf518e1eb',`Porsche SHA mismatch: ${digest}`);
console.log(JSON.stringify({status:'PASS',porscheSha256:digest,rootPosition:[-1,-0.028,0],rootRotationY:'PI',legacySuppressed:['kerb','rail','vegetation'],lighting:'world-space',exposure:0.94,shadowMap:'PCFSoftShadowMap'},null,2));
