#!/usr/bin/env python3
"""Deterministic Y004 procedural ambient sound bed, NO NARRATION.
Only a provisional 24s reference. Manager must retime from measured new VO.
No unlicensed recordings and no external inputs.
"""
import argparse
import hashlib
import json
import math
import pathlib
import subprocess
import tempfile
import wave

import numpy as np
from scipy.signal import butter, sosfilt


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--output', required=True, help='48 kHz stereo AAC in M4A file')
    ap.add_argument('--frames', type=int, default=720, help='PROVISIONAL unless Manager locked')
    a = ap.parse_args()
    if not (120 <= a.frames <= 1800):
        raise SystemExit('frames must be an integer between 120 and 1800')
    rate, fps = 48000, 30
    n = a.frames * rate // fps
    t = np.arange(n) / rate
    duration = n / rate
    rng = np.random.default_rng(4004)

    # Demonstration staging only, NOT an OEM speed/engine calibration.
    speed = np.interp(t / duration, [0, .10, .34, .40, .55, .78, 1], [.24, .30, .35, .50, .66, .71, .80])
    rpm_freq = 56 + 44 * speed
    phase = np.cumsum(2 * np.pi * rpm_freq / rate)
    engine = (.012 * np.sin(phase) + .005 * np.sin(phase * 2) + .003 * np.sin(phase * 3)) * (.5 + .5 * speed)
    def filter_noise(sos, amp):
        return sosfilt(sos, rng.standard_normal(n)).astype(np.float64) * amp
    road = filter_noise(butter(2, [145, 1900], btype='bandpass', fs=rate, output='sos'), .0026) * (0.4 + 1.0 * speed)
    wind = filter_noise(butter(2, [500, 4500], btype='bandpass', fs=rate, output='sos'), .0013) * (0.2 + 1.5 * speed)
    # Gentle, nonliteral roadside pass: a gain + pan contour, no harsh whoosh.
    pos = t / duration
    pass_env = np.exp(-.5 * ((pos-.885)/.034)**2)
    pass_noise = filter_noise(butter(2, [250, 3800], btype='bandpass', fs=rate, output='sos'), .0033) * pass_env
    bed = engine + road + wind
    start_end = np.minimum(np.clip(t / .25, 0, 1), np.clip((duration - t)/.35,0,1))
    bed *= start_end
    left = (bed + pass_noise * np.sqrt(np.maximum(0,1-pos)))
    right = (bed + pass_noise * np.sqrt(np.maximum(0,pos)))
    stereo = np.stack((left, right), axis=1)
    peak = float(np.max(np.abs(stereo)))
    if not math.isfinite(peak) or peak > .3:
        raise SystemExit(f'bed peak unsafe: {peak}')

    out = pathlib.Path(a.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as td:
        wav = pathlib.Path(td)/'bed.wav'
        with wave.open(str(wav),'wb') as w:
            w.setnchannels(2);w.setsampwidth(2);w.setframerate(rate)
            w.writeframes(np.round(np.clip(stereo,-1,1)*32767).astype('<i2').tobytes())
        subprocess.run(['ffmpeg','-y','-v','error','-i',str(wav),'-ar','48000','-ac','2','-c:a','aac','-b:a','192k','-movflags','+faststart',str(out)],check=True)
    subprocess.run(['ffmpeg','-v','error','-xerror','-i',str(out),'-f','null','-'],check=True)
    probe=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_entries','format=duration:stream=codec_name,sample_rate,channels','-of','json',str(out)]))
    assert probe['streams'][0]['codec_name']=='aac' and int(probe['streams'][0]['sample_rate'])==rate and probe['streams'][0]['channels']==2
    assert abs(float(probe['format']['duration'])-duration)<.01
    result={'status':'PROVISIONAL_EFFECTS_ONLY_NOT_NARRATION_OR_FINAL_MIX','source':'local deterministic numpy/scipy procedural synthesis, no third-party recordings','rights':'generated by Agent D from mathematical waveforms','fps':fps,'frames':a.frames,'duration_seconds':duration,'sample_rate_hz':rate,'channels':2,'decoded_float_peak':peak,'file':out.name,'sha256':hashlib.sha256(out.read_bytes()).hexdigest(),'bytes':out.stat().st_size}
    (out.parent/(out.stem+'.json')).write_text(json.dumps(result,indent=2)+'\n')
    print(json.dumps(result,indent=2))

if __name__ == '__main__':main()
